name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"
      - "develop"

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "pnpm"
          node-version: "20"

      - name: "Install pnpm"
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: "Install npm dependencies"
        run: "pnpm install"

      - name: "Lint the contracts"
        run: "npm run lint"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test